### ISSUE TITLE
The input search on documentation´s page is not working correctly

### ISSUE THREAD

**Issue by hnrqsss** [facebook/react-native-website#998] opened 2019-06-07 17:59 UTC
On the react-native's page the input on the right top of the page doesn't works.
[https://facebook.github.io/react-native/](https://facebook.github.io/react-native/)

React Native version: 0.59
Mac OS  10.14.5 Mojave

Before this bug when i'm  write something in the input and if there is a match with i wrote, shows at the bottom of the input. Today nothing appears even when i press enter. 

## Steps To Reproduce

1. [bug's image](https://drive.google.com/file/d/1i3jLV8xZfsTwg4jXZszfIlbarGXpmOey/view)

**Comment by nitaking** [comment] 2019-06-10 07:17
It seems to occur only on the top page.

![2019-06-10 16 15 59](https://user-images.githubusercontent.com/10850034/59178841-29dc3580-8b9b-11e9-94f5-79f95914c9a7.gif)
![2019-06-10 16 16 16](https://user-images.githubusercontent.com/10850034/59178848-2e085300-8b9b-11e9-992c-1a5b71feb5be.gif)

**Comment by methodbox** [comment] 2019-06-10 22:25
> It seems to occur only on the top page.
> 
> ![2019-06-10 16 15 59](https://user-images.githubusercontent.com/10850034/59178841-29dc3580-8b9b-11e9-94f5-79f95914c9a7.gif)
> ![2019-06-10 16 16 16](https://user-images.githubusercontent.com/10850034/59178848-2e085300-8b9b-11e9-992c-1a5b71feb5be.gif)

I'm not sure WTF is happening in your GIF (why is there 2 instances of the site on two different pages?) but it's broken for me for the entire site.

I was only able to get it to work again by clearing cache in Chrome which makes me suspect it's related to garbage collection somehow, or how the site sets cookies.

There is a suggestion in another thread that only the drop-down for the smart search isn't working; for me it just didn't do anything even after hitting Enter to search:  https://github.com/facebook/react-native-website/issues/61 - I also didn't see the drop-down.

It seems to work from the landing page, but only intermittently.

This issue is also a duplicate of this issue: https://github.com/facebook/react-native-website/issues/985.

I would be willing to be the appearance of the drop-down for the quick search and the Enter button issue are related ...

**Comment by methodbox** [comment] 2019-06-13 15:45
Not sure if you guys saw, but this is resolved now per: https://github.com/facebook/react-native-website/issues/61

So this one can probably be closed.

**Closed** 2019-06-13 15:52 UTC
