### ISSUE TITLE
Hi, I would like to collaborate with your project by serving as a translator into Spanish, which is my native language. I would like to translate the document README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by LuigiBaute** [facebook/react-native-website#204] opened 2018-02-18 19:49 UTC

**Comment by charpeni** [comment] 2018-02-19 18:15
Duplicate of #181.

Please see this answer: https://github.com/facebook/react-native-website/issues/181#issuecomment-363261257

**Closed by charpeni** 2018-02-19 18:15 UTC
