### ISSUE TITLE
PickerIOS这一节太丑了，不知道什么时候加了个css,希望改进一下

### ISSUE THREAD

**Issue by autumnleaves1** [facebook/react-native-website#1007] opened 2019-06-12 03:48 UTC
![image](https://user-images.githubusercontent.com/23214175/59322261-eeab4500-8d07-11e9-857d-a2f80b76cc5c.png)
![image](https://user-images.githubusercontent.com/23214175/59322289-08e52300-8d08-11e9-89c5-6478de39a52e.png)

**Comment by rickhanlonii** [comment] 2019-06-12 11:02
Hey @autumnleaves1, thanks for filing an issue. Can you help me understand what the issue is here? I can't tell from the screenshots.

**Comment by autumnleaves1** [comment] 2019-06-12 11:29
Sorry,I did not describe my point clearly.
I just want to say that the list on left in the first picture should be left and should not be moved. That should be like the second picture。
I think it should be that your adaptation is not doing well.
As a programmer, looking at the uncomfortable
![image](https://user-images.githubusercontent.com/23214175/59347769-16220200-8d48-11e9-9714-62cd908270d5.png)

![image](https://user-images.githubusercontent.com/23214175/59347803-2934d200-8d48-11e9-8922-b38e2c2c6b2e.png)

**Comment by Simek** [comment] 2020-05-13 18:22
Hi @autumnleaves1, it seems to me that after the website redesign it is not long an issue. 

I'm going to close this for now. If you are experiencing similar issues with the new design please create the new issue. 

P.S. AFAIK `https://reactnative.cn` in not a part of the official website and this issue shouldn't be reported in this repository in the first place.

**Closed by Simek** 2020-05-13 18:22 UTC
