### ISSUE TITLE
Navigator page: anchor tags lead to 404 pages, Edit link leads to github 404

### ISSUE THREAD

**Issue by quetzaluz** [facebook/react-native-website#1427] opened 2019-10-23 23:08 UTC
To reproduce:
- Visit https://facebook.github.io/react-native/docs/0.43/navigator.html
- Click any of the method links, for example onWillFocus
- You arrive at a 404 page at that route: https://facebook.github.io/react-native/docs/0.43/navigator.md#onwillfocus
<img width="904" alt="Screen Shot 2019-10-23 at 4 08 20 PM" src="https://user-images.githubusercontent.com/3665912/67440841-60957400-f5af-11e9-81ca-c92149b0b9e9.png">

Currently observed only on the navigator docs page.

**Comment by quetzaluz** [comment] 2019-10-25 16:31
Noting that this is also occuring for https://facebook.github.io/react-native/docs/0.43/navigatorios

Affected pages also lead to github 404 pages when you click edit, ex https://github.com/facebook/react-native-website/blob/master/docs/navigatorios.md

issue seems to be when these pages do not exist in the root docs directory

**Comment by samslow** [comment] 2019-11-02 07:32
This problem occurs in more places than you think.
I've had the same problem with the flatlist.
What these problems have in common is that they are linked to '.md'

I'll fix it.

**Comment by rachelnabors** [comment] 2020-02-26 15:19
Thanks for the heads up!

I think I see what the issue is: these links use `<componentname>.md#<anchor>` in the link name instead of `<componentname>#<anchor>` or even `<anchor>`. The solution is to scour the docs for `.md#` and replace those with `#`. It would make a fine first time contribution. Any takers?

**Comment by mdb1710** [comment] 2020-02-26 15:46
> Thanks for the heads up!
> 
> I think I see what the issue is: these links use `<componentname>.md#<anchor>` in the link name instead of `<componentname>#<anchor>` or even `<anchor>`. The solution is to scour the docs for `.md#` and replace those with `#`. It would make a fine first time contribution. Any takers?

I would be happy to tackle this for you.

**Comment by rachelnabors** [comment] 2020-02-26 15:52
I'll assign it to you then. Good luck, and if you get stuck, DM me!

**Comment by yozaam** [comment] 2020-05-03 13:53
Hey, I see that it is assigned but since he/she is inactive, I would love to do this

**Comment by mdb1710** [comment] 2020-05-03 14:49
> Hey, I see that it is assigned but since he/she is inactive, I would love to do this
> Sorry if it is a noob question,
> The changes need to be made in every file in /website/versioned_docs or in /docs as well?
> Or only in docs and docs is compiled into versioned_docs?
> https://github.com/facebook/react-native-website#versioned-docs
> 
> Also if I need to change the versioned_docs, there were more than 14.5k occurances of ".md#" in versioned_docs so I what tests can I do to make sure I didn't break anything?

Hi @yozaam  I have already finished and sent the PR for this issue just waiting for the review and approval.

**Comment by yozaam** [comment] 2020-05-07 04:56
Oops 🙈  superb :D

**Comment by jpbulman** [comment] 2020-05-31 20:25
The pr for this [closed](https://github.com/facebook/react-native-website/pull/1830), anyone care if I pick this up?

**Comment by Simek** [comment] 2020-05-31 20:51
@jpbulman Feel free to work on this! 

The best way to fix those issues is just to remove the in-content links in the versioned docs page. Those parts are the relict of the past when there was no right sidebar on the website (previous design). Now they are redundant (and cause some problems in the older docs).

The another benefit of removal approach will be the faster generation of `metadata.js` and thus quicker build and deploy (in theory, but it depends on the amount of removed links).

**Comment by jpbulman** [comment] 2020-05-31 21:36
@Simek So can I just remove the ```methods``` and ```props``` sections (under ```scene transitions```) completely?

**Comment by Simek** [comment] 2020-05-31 21:44
Yes, you can check the #1901 PR for the reference/example. The same links are now automatically generated and added to the right sidebar by the Docusaurs.

<img width="790" alt="Annotation 2020-05-31 234354" src="https://user-images.githubusercontent.com/719641/83363288-9fd34100-a398-11ea-8f58-0edad67b47f2.png">

**Comment by jpbulman** [comment] 2020-05-31 23:54
@Simek great, thanks! I've started clearing out those sections in some of the components, and I came across another dead link. In [NavIOS 0.43](https://github.com/facebook/react-native-website/blob/master/website/versioned_docs/version-0.42/navigatorios.md), it says something like 'Take a look at _Navigator_ ...' in the second paragraph. It tries to reference ```navigator.md```, but since it's not in the same directory, it fails. How can I reference the markdown file outside its directory? I tried ```../version-0.5/navigator.md```, but that didn't seem to work.

**Comment by jpbulman** [comment] 2020-06-01 00:06
Oh I see, it's because navigator is deprecated so it doesn't make it into the ```docs``` directory. Is there any way to reference files from older versions, or does it have to be a link with a hard-coded url?

**Comment by Simek** [comment] 2020-06-02 17:38
@jpbulman The regular, in text, links should be replaced with versions without extension (`.md`). And yes, the `Navigator` case is a bit specific since this module has be completely removed from the core and the way you have updated the link should be correct.

**Comment by jpbulman** [comment] 2020-06-03 16:51
@Simek I started a pr for this [here](#1970 )

**Closed** 2020-06-18 09:03 UTC
Labels: Good first issue
