### ISSUE TITLE
Dead Roadmap Wiki Link

### ISSUE THREAD

**Issue by jpbulman** [facebook/react-native-website#1964] opened 2020-05-31 20:03 UTC
## Description

At the bottom of the road map [page](https://github.com/facebook/react-native/wiki/Roadmap) in the main repo under the _communication_ section, there is a dead link. 

## What is the problem?

The link for 'top open source projects on GitHub' no longer works and goes to a 404.

## How can we address it?

Octoverse has moved all of their rankings to their [front page](https://octoverse.github.com/), so the link could potentially be swapped out with that.

## Why is it important?

It's not really important - but I just figure it's an easy fix to help make the claim still cited.

## Who needs this?

Anyone who might be looking at the roadmap. 

## When should this happen (use version numbers if needed)?

Any point when someone with write access to the wiki might get bored

**Comment by Simek** [comment] 2020-05-31 20:37
Hi @jpbulman, thank you for bringing this up, but this is the React Native **website** repository. 

As you stated in the first sentence the wiki page with the issue is a part of the main React Native repository, so please open an issue in there. Not the same group of people manage those both repositories.

BTW. The the mentioned above dead link has been fixed on the website side within PR #1488.

**Closed by Simek** 2020-05-31 20:37 UTC
