### ISSUE TITLE
"Setting up the development environment" webpage - Can't select macOS and iOS options, automatic upward scrolling is happening

### ISSUE THREAD

**Issue by vikramvi** [facebook/react-native-website#2806] opened 2021-10-06 11:15 UTC
## Description

1. Goto https://reactnative.dev/docs/environment-setup
2. Try to select macOS and iOS
3. Selection can't be done from **Mac 11.5.2** with **Chrome 94.0.**
4. Also if I am in the bottom portion of the webpage; it automatically scrolls upwards
5. I checked console log but there is no error
6. Issue is reproducible with **incognito mode Chrome browser** and **FF 92.0**

Expected Result:
1. Correct development OS should have been selected when I visit this webpage
2. User should be able to select options easily
3. Autoscrolling shouldn't happen, it's very annoying and can't use the website

## Documentation version

0.66 ( https://reactnative.dev/docs/environment-setup )

**Comment by Simek** [comment] 2021-10-06 11:26
Duplicate of #2771.

Hi @vikramvi, thank you for the report! 👍 

This is a bit weird that it happens for you on different browsers. Can you try clear the cache or hard reloading the webpage? If this do not help please join the discussion in the reference issue.

**Closed by Simek** 2021-10-06 11:26 UTC

**Comment by vikramvi** [comment] 2021-10-07 05:14
@Simek  please refer to Pt. 6  `Issue is reproducible with incognito mode Chrome browser ....` so it does happen with and without cache
