### ISSUE TITLE
Latest (RC) build breaks links in articles

### ISSUE THREAD

**Issue by philipp-spiess** [facebook/react-native-website#505] opened 2018-08-09 09:52 UTC
I just stumbled over a dead link in one of the RN guides, specifically the link to the Animations guide in: https://facebook.github.io/react-native/docs/animated

After looking into the markdown source the link is correct. It seems like the build process generate version-specific links: `https://facebook.github.io/react-native/docs/0.57-RC/animations#animated-api` this seems like a good idea however for the current `0.57-RC` build, which is served as the default version, the version-specific link results in a 404. Using a previous version works as expected: https://facebook.github.io/react-native/docs/0.56/animations#animated-api

Maybe the current version should not include the version identifier but links to the default guide instead?

**Comment by charpeni** [comment] 2018-08-09 13:01
Thanks for catching this!

@hramos @endiliey It looks like `defaultVersionShown ` is not used once we're on a doc 🤔 .

**Comment by endiliey** [comment] 2018-08-09 14:18
Hi @charpeni, can I clarify the wanted behavior ? If this is correct, I can start working on a fix.

## Bug

If the current `defaultVersionShown` is 0.56.

*Wanted Behavior*
https://facebook.github.io/react-native/docs/animations#animated-api is v0.56 docs
and https://facebook.github.io/react-native/docs/0.57-RC/animations#animated-api is v0.57-RC docs

*Current Behavior*
https://facebook.github.io/react-native/docs/animations#animated-api is v0.57-RC docs
and https://facebook.github.io/react-native/docs/0.56/animations#animated-api is v0.56 docs

## Quick Investigation

Seems to me this is caused by incomplete PR https://github.com/facebook/Docusaurus/pull/639 that rename `latestVersion` to `defaultVersion`. There is still some part of our codes still using `latestVersion`.

Example: https://github.com/facebook/Docusaurus/blob/e27e18bd63bc0c8c7fa24306b5594411af059df0/lib/server/versionFallback.js#L178

cc @JoelMarcey @yangshun

**Comment by JoelMarcey** [comment] 2018-08-09 16:30
@charpeni Interesting catch here. Thanks.

@endiliey I believe it was always the intention to have the latest version not have an explicit version in the link. If you choose a `defaultVersionShown` that is not the latest version, while it is shown by default, it still shows the version number in the link. So I think the current behavior is the one we always wanted. `next` is always shown for stuff that hasn't been versioned yet.

That said, we have now run into this buggy case. There are two options, I think:

1. Change the current behavior to the wanted behavior. Does that break anything?
2. For the latest version, build links to other docs without the version number so that the current behavior can continue to work.

I am open to discussing which one is better.

**Comment by endiliey** [comment] 2018-08-09 17:03
Changing the behavior to no 1 might potentially break someone's else website since it has been the current behavior for quite a while. Since it is intended, fix no 2 shouldn't be too hard. Just a matter on how we build the link.

I could send a fix (or anyone who wanted to send a PR to Docusaurus 😉) when everyone agrees on which options we are going ahead with.

**Comment by charpeni** [comment] 2018-08-09 18:45
Thanks all, I've removed `defaultVersionShown` for now, let's close this issue.

**Closed by charpeni** 2018-08-09 18:45 UTC
