### ISSUE TITLE
React Native Components Known issues

### ISSUE THREAD

**Issue by Ashoat** [facebook/react-native-website#564] opened 2018-09-17 17:23 UTC
After some discussion [here](https://github.com/react-native-community/discussions-and-proposals/issues/9), we've decided to start adding "known issues" sections to the docs pages for components.

This is the "known issue" definition we agreed on:

> is a way more relaxed interpretation of the word issue: it is something that you will face when using React Native that may or may not be a bug, and may not be caused by React Native. And when there is a known issue usually I can also expect a workaround to be written there.

## Purpose of this issue

1. To reference the Markdown template we'll use for listing these issues, as well as an example PR that adds a "known issues" section.
2. To list GitHub issues for each component that should be added to that component's docs page.

## Request for help

1. For each component, we need to do a bit of research to figure out what the current "Known issues" are. If you can find any issues that you think should be given high visibility to people looking to use a particular component, then please comment them below and we'll add them to the "No PR yet" list.
2. Once a component has some entries under "No PR yet" below, we need somebody to create a PR on `react-native-website` adding the "known issues" section. Reference the template below and [this example PR](https://github.com/facebook/react-native-website/pull/519) to get an idea of what this should look like.

## Example template

```md
# Known issues

* [react-native#18997](https://github.com/facebook/react-native/issues/18997): Doesn't support multiline `TextInput`s
* [react-native#20157](https://github.com/facebook/react-native/issues/20157): Can't use with a bottom tab bar
```

#### ActivityIndicator
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### Animated
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### AsyncStorage
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### Button
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### DatePickerIOS
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### DrawerLayoutAndroid
* ##### No PR yet
* ##### PR in review
* ##### PR merged
#### FlatList
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### Image
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### InputAccessoryView
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
    * [react-native#18997](https://github.com/facebook/react-native/issues/18997): Doesn't support multiline `TextInput`s
    * [react-native#20157](https://github.com/facebook/react-native/issues/20157): Can't use with a bottom tab bar
#### KeyboardAvoidingView
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### MaskedViewIOS
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### Modal
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### PanResponder
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### Picker
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### PickerIOS
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### ProgressBarAndroid
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### ProgressViewIOS
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### RefreshControl
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### SafeAreaView
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### ScrollView
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### SectionList
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### SegmentedControlIOS
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### Slider
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### SnapshotViewIOS
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### StatusBar
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### Switch
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### TabBarIOS
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### Text
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### TextInput
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### ToolbarAndroid
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### TouchableHighlight
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### TouchableNativeFeedback
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### TouchableOpacity
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### TouchableWithoutFeedback
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### View
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### ViewPagerAndroid
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### VirtualizedList
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅
#### WebView
* ##### No PR yet 🚫
* ##### PR in review 💫
* ##### PR merged ✅

**Comment by kelset** [comment] 2018-12-17 12:12
Found a potential known issue -> https://github.com/facebook/react-native/issues/16263 (seems to be caused by Google, look at the last comment)

**Comment by Simek** [comment] 2020-11-03 13:28
@Ashoat @kelset Hey guys! 👋 What is the status of this issue, do we still need it? Are there any know issues missing on the website?

**Comment by kelset** [comment] 2020-11-03 13:42
well it wasn't updated since Dec 2018 so more or less 20 years ago... so I'd say let's close it :D

**Closed by kelset** 2020-11-03 13:42 UTC
Labels: 👋 Good first issue

**Comment by a-eid** [comment] 2021-01-11 22:47
@kelset so is there any plans to improve the react-native lists components ?
